db:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    MYSQL_DATABASE: todobackend
    MYSQL_USER: todo
    MYSQL_PASSWORD: Mysql@1234
    MYSQL_ROOT_PASSWORD: Mysql@1234


app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes_from:
    - webroot
  links:
    - db
  environment:
    DJANGO_SETTINGS_MODULE: todobackend.settings.release
    MYSQL_HOST: db
    MYSQL_USER: todo
    MYSQL_PASSWORD: Mysql@1234
  command:
    - uwsgi
    - "--socket /var/www/todobackend/todobackend.sock"
    - "--chmod-socket=666"
    - "--module todobackend.wsgi"
    - "--master"
    - "--die-on-term"



webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /var/www/todobackend
  entrypoint: "true"

agent:
  image: kris1408/ansible
  volumes:
    - ../../ansible/probe.yml:/ansible/site.yml
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"

nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./todobackend.conf:/etc/nginx/conf.d/todobackend.conf
  ports:
    - "8000:8000"
  volumes_from:
    - webroot


test:
  image: kris1408/todobackend-specs
  links:
    - nginx
  environment:
    URL: http://nginx:8000/todos
    JUNIT_REPORT_PATH: /reports/acceptance.xml
    JUNIT_REPORT_STACK: 1
  command: --reporter mocha-jenkins-reporter
